name: Registry express proxy image to Docker Hub
on: [workflow_dispatch]
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./express-proxy
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO_NAME_EXPRESS}}:latest-${{github.run_number}}
